### Оптимизация

In [23]:
from scipy import optimize

def f(x):
    return (x[0]-5)**2 + (x[1]+2)**3 - 17

#Минимум функции
print "F min =",optimize.minimize(f,[-1000,1000])

F min =       fun: -16.999999995806757
 hess_inv: array([[  3.92908611e-01,   2.25746144e-03],
       [  2.25746144e-03,   4.87859184e+01]])
      jac: array([ -2.38418579e-07,   7.62939453e-06])
  message: 'Optimization terminated successfully.'
     nfev: 132
      nit: 29
     njev: 33
   status: 0
  success: True
        x: array([ 4.99999993, -1.99838744])


### Вектора

In [65]:
from numpy.linalg import norm
from scipy.spatial.distance import cdist

vector = np.array([1,-2,3,-4,7])
vector2 = np.array([-6,-6,4,8,9])
print "Векторы:",vector,"\n",vector2,"\n"

#Норма - длина вектора
print "Норма L1=",norm(vector,ord=1),"\nНорма L2=",norm(vector,ord=2)

#Метрика - расстояние между векторами
print "Расстояние L1=",norm(vector-vector2,ord=1)
print "Расстояние L2=",cdist(vector[np.newaxis,:],vector2[np.newaxis,:],metric='euclidean')

#Косинусное расстояние
print "\nCos=",np.dot(vector,vector2)/norm(vector)/norm(vector2)

#Изменение размерности
print "\nИзменение размерности: ",vector.reshape((1,5))
print "Добавление фиктивной строки:",vector2[np.newaxis,:]

Векторы: [ 1 -2  3 -4  7] 
[-6 -6  4  8  9] 

Норма L1= 17.0 
Норма L2= 8.88819441732
Расстояние L1= 26.0
Расстояние L2= [[ 14.62873884]]

Cos= 0.361164099419

Изменение размерности:  [[ 1 -2  3 -4  7]]
Добавление фиктивной строки: [[-6 -6  4  8  9]]


### Матрицы

In [69]:
#Решение системы уравнений
from scipy import linalg
koef_matrix = np.array([[1,7,3],[-5,4,9],[-5,-8,3]])
print "Исходная матрица:\n",koef_matrix
y = [5,6,3]
x = linalg.solve(koef_matrix,y)
print "\nx=",x

#Скалярное произведение или умножение
print "y=",np.dot(koef_matrix,x)

#Определитель
print "det=",np.linalg.det(koef_matrix)

#Ранг
print "rang=",np.linalg.matrix_rank(koef_matrix)

#Транспонирование
print "\nТранспонирование:\n",np.transpose(koef_matrix)

#Обращение
print "\nОбращение:\n",np.linalg.inv(koef_matrix)

#Собственные числа и вектора
w,v = np.linalg.eig(koef_matrix)
print "\nСобственные числа:",w
print "\nСобственные вектора:\n",v

Исходная матрица:
[[ 1  7  3]
 [-5  4  9]
 [-5 -8  3]]

x= [ 5.61111111 -2.11111111  4.72222222]
y= [ 5.  6.  3.]
det= 54.0
rang= 3

Транспонирование:
[[ 1 -5 -5]
 [ 7  4 -8]
 [ 3  9  3]]

Обращение:
[[ 1.55555556 -0.83333333  0.94444444]
 [-0.55555556  0.33333333 -0.44444444]
 [ 1.11111111 -0.5         0.72222222]]

Собственные числа: [ 0.39123869 +0.j          3.80438065+11.11529784j  3.80438065-11.11529784j]

Собственные вектора:
[[ 0.77560086+0.j          0.25568834-0.37966285j  0.25568834+0.37966285j]
 [-0.30443327+0.j          0.65048307+0.j          0.65048307-0.j        ]
 [ 0.55295903+0.j          0.12791052+0.59244432j  0.12791052-0.59244432j]]
