## Определение спама в СМС

In [25]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LogisticRegression

In [26]:
#Загрузим данные
data = pd.read_csv('../Data/SMSSpamCollection.txt', delimiter='\t',header=None,names=['label', 'sms'])
y = np.where(data.label == 'ham',0,1)
sms = data.sms

In [27]:
#Сформируем матрицу признаков
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sms)
print (X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
#Оценим модель логистиеской регрессии
log_model = LogisticRegression(random_state=2)
results = cross_val_score(log_model, X, y, cv=10, scoring='f1')
print('Mean: ',results.mean())
print('Results: ',results)

Mean:  0.9326402983610631
Results:  [0.95890411 0.89855072 0.91549296 0.95833333 0.93706294 0.91304348
 0.94444444 0.92753623 0.92198582 0.95104895]


In [31]:
#Обучим модельна всей выборке
log_model.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=2, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
#Сделаем пару предсказаний
test_sms = ["FreeMsg: Txt: CALL to No: 86888 & claim your reward of 3 hours talk time to use from your phone now! Subscribe6GB"
,"FreeMsg: Txt: claim your reward of 3 hours talk time"
,"Have you visited the last lecture on physics?"
,"Have you visited the last lecture on physics? Just buy this book and you will have all materials! Only 99$"
,"Only 99$"]

log_model.predict(vectorizer.transform(test_sms))

array([1, 1, 0, 0, 0])